### ISSUE TITLE
Custom templates

### ISSUE THREAD

**Issue by ebramanti** [iVantage/angular-ivh-multi-select#13]
Does multi select allow for custom templates like `angular-ivh-treeview` does? It isn't very apparent from the README.

**Comment by jtrussell** [comment]
Sorry, it does not. You can do quite a bit with label expressions but we're still assuming bootstrap, and the controls aren't really customizable.

Treeview was written from the ground up to be customizable while this directive came to exist because we ran into performance issues with another multi-select solution and needed an alternative quickly. As a result it assumes a fair bit about your styles choices.

**Comment by ebramanti** [comment]
@jtrussell I'm running up against treeview's performance wall, but I need custom templates to fit with the style of app I'm trying to build. I'll keep looking, thanks for letting me know 👍
